//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMaps
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchase_price
    {
        public string ID { get; set; }

        [Display(Name = "VN")]
        [Required(ErrorMessage = "Required VN")]
        public double VN { get; set; }

        [Display(Name = "TG")]
        [Required(ErrorMessage = "Required TG")]

        public double TG { get; set; }

        [Display(Name = "Ngày")]
        [Required(ErrorMessage = "Required Date")]

        public System.DateTime DATE_DETAIL { get; set; }
    }
}
